export const FETCH_PROJECTS = `FETCH_PROJECTS`;
export const OPEN_PROJECT_DIALOG = `OPEN_PROJECT_DIALOG`;
export const CLOSE_PROJECT_DIALOG = `CLOSE_PROJECT_DIALOG`;
export const OPEN_PROFILE_DIALOG = `OPEN_PROFILE_DIALOG`;
export const CLOSE_PROFILE_DIALOG = `CLOSE_PROFILE_DIALOG`;
export const SELECT_PROJECT = `SELECT_PROJECT`;
export const SHOW_PROJECT_THUMBNAILS_IN_PROJECT_DIALOG = `SHOW_PROJECT_THUMBNAILS_IN_PROJECT_DIALOG`;

export const ACCESS_TOKEN = 'accessToken';

export const LOGIN = `LOGIN`;
export const LOGOUT = `LOGOUT`;
export const FETCH_PROJECTS_FOR_DASHBOARD = `FETCH_PROJECTS_FOR_DASHBOARD`;
export const OPEN_DELETE_PROJECT_DIALOG = `OPEN_DELETE_PROJECT_DIALOG`;
export const CLOSE_DELETE_PROJECT_DIALOG = `CLOSE_DELETE_PROJECT_DIALOG`;

export const SHOW_PROGRESS_OVERLAY = `SHOW_PROGRESS_OVERLAY `;
export const HIDE_PROGRESS_OVERLAY = `HIDE_PROGRESS_OVERLAY `;
export const SHOW_SNACKBAR = `SHOW_SNACKBAR`;
export const HIDE_SNACKBAR = `HIDE_SNACKBAR`;
export const UPDATING_PROJECT = `UPDATING_PROJECT`;
export const FINISHED_CREATING_UPDATING_PROJECT = `FINISHED_CREATING_UPDATING_PROJECT`;

export const BASE_API_URL = 'https://PortfolioApi-env.vwphbpfx2y.us-east-1.elasticbeanstalk.com/'